server:
  port: 8080

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    enabled: true
    encoding: UTF-8
    url: jdbc:mysql://localhost:3306
    init-sqls: CREATE SCHEMA IF NOT EXISTS `english_dictionary` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
    schemas: ${DB_SCHEMA}
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver